steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo 'GOOGLE_ANALYTICS_ID="${_GOOGLE_ANALYTICS_ID}"' > .env
        echo 'NEXT_PUBLIC_GOOGLE_CLIENT_ID="${_NEXT_PUBLIC_GOOGLE_CLIENT_ID}"' > .env
        echo 'OGP_IMAGE_PATH ="${_OGP_IMAGE_PATH }"' > .env
        cat .env

  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install']

  - name: 'gcr.io/cloud-builders/yarn'
    args: ['run', 'build']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'app',
        'deploy',
        '--appyaml=./deploy/app.yaml',
        '--stop-previous-version',
        '--quiet',
      ]
